security:
  referrerPolicy: 'origin'
port: 3100
timeout: 30000
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  name: 'fis_ds_update'
  maxAge: 1260000
  PORT: 6380
  TLS: true
  CONNECTION_TIMEOUT: 15000
  COOKIE_MAX_AGE: 21
  redis:
    host:
    key:
  secureCookie: 'true'
api:
  cos: FIS_COS_API
  serviceAuth: RPE_API
uploadPolicy:
  documentSize: 20
  multimediaSize: 500
  maxNoOfFiles: 10
app:
  caseTypeOfApplication: 'RELADOP'
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
s2s:
  microservice: 'fis_ds_update_web'
documentManagement:
  uploadSizeinMB: 30
cookies:
  expiryTime: 365
  cookieName: 'ds-web-update-cookie-preferences'
loggedInUsers: ['legalRep', 'police']
