security:
  referrerPolicy: 'origin'
port: 3100
timeout: 30000
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
api:
  cos: 'https//fis-cos-api-pr-140.service.core-compute-preview.internal'    
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey: